// Package dto contains the types for schema 'public'.
package dto

// Code generated by xo. DO NOT EDIT.

import (
	"gopkg.in/guregu/null.v3"
)

// PaymentType represents a row from 'public.payment_types'.
type PaymentType struct {
	ID         int         `db:"id"`          // id
	Name       null.String `db:"name"`        // name
	Display    null.String `db:"display"`     // display
	CreateDate null.Time   `db:"create_date"` // create_date
	UpdateDate null.Time   `db:"update_date"` // update_date
}
