// Package dto contains the types for schema 'public'.
package dto

// Code generated by xo. DO NOT EDIT.

import (
	"github.com/ShingoYadomoto/ushijima/server/domain/model"
	"gopkg.in/guregu/null.v3"
)

// Payment represents a row from 'public.payments'.
type Payment struct {
	ID              int       `db:"id"`                // id
	PaymentTypeID   null.Int  `db:"payment_type_id"`   // payment_type_id
	PaymentStatusID null.Int  `db:"payment_status_id"` // payment_status_id
	Amount          null.Int  `db:"amount"`            // amount
	CreateDate      null.Time `db:"create_date"`       // create_date
	UpdateDate      null.Time `db:"update_date"`       // update_date
	MonthID         null.Int  `db:"month_id"`          // month_id
}

func (p *Payment) ToModel() *model.Payment {
	return &model.Payment{
		ID:              model.PAYMENT_ID(p.ID),
		PaymentTypeID:   model.PAYMENT_TYPE_ID(p.PaymentTypeID.Int64),
		PaymentStatusID: model.PAYMENT_STATUS_ID(p.PaymentStatusID.Int64),
		MonthID:         model.MONTH_ID(p.MonthID.Int64),
		Amount:          int(p.Amount.Int64),
	}
}
