// Package model contains the types for schema 'public'.
package model

// Code generated by xo. DO NOT EDIT.

import (
	"gopkg.in/guregu/null.v3"
)

// PaymentType represents a row from 'public.payment_types'.
type PaymentType struct {
	ID         int         `db:"id" json:"id"`                   // id
	Name       null.String `db:"name" json:"name"`               // name
	Display    null.String `db:"display" json:"display"`         // display
	CreateDate null.Time   `db:"create_date" json:"create_date"` // create_date
	UpdateDate null.Time   `db:"update_date" json:"update_date"` // update_date
}
